In [1]:
import numpy as np

stock1 = np.array([
    [100, 110, 95],
    [102, 112, 97],
    [105, 115, 100],
    [108, 118, 102],
    [110, 120, 105]
])

stock2 = np.array([
    [98, 108, 94],
    [101, 111, 96],
    [103, 113, 98],
    [107, 117, 101],
    [109, 119, 104]
])

sum_matrix = stock1 + stock2

diff_matrix = stock1 - stock2

print("Stock 1 Data:\n", stock1)
print("Stock 2 Data:\n", stock2)

print("Element-wise Sum:\n", sum_matrix)
print("Element-wise Difference:\n", diff_matrix)

Stock 1 Data:
 [[100 110  95]
 [102 112  97]
 [105 115 100]
 [108 118 102]
 [110 120 105]]
Stock 2 Data:
 [[ 98 108  94]
 [101 111  96]
 [103 113  98]
 [107 117 101]
 [109 119 104]]
Element-wise Sum:
 [[198 218 189]
 [203 223 193]
 [208 228 198]
 [215 235 203]
 [219 239 209]]
Element-wise Difference:
 [[2 2 1]
 [1 1 1]
 [2 2 2]
 [1 1 1]
 [1 1 1]]
